### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by wujun4code** [wujun4code/bas-web#1]
## 前期需要做硬件基础

- [ ] bizapp.store  域名购买
- [ ] 一台可以在国内正常访问服务器
- [ ] cloudflare 域名解析

## 基础架构
- [ ] Parse 后端服务的 Docker 环境搭建
- [ ] Parse SDK for Angular 的编写
- [ ] LetsEncript  证书的自动续约

## 内容编辑

- [ ] 结构数据的输入
- [ ] 第一批入库的 SaaS 企业服务
